### ISSUE TITLE
cannot work in boot 2.0.0

### ISSUE THREAD

**Issue by bianbian-org** [paypal/resteasy-spring-boot#90]
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724) ~[?:1.8.0_141]
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531) ~[?:1.8.0_141]
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355) ~[?:1.8.0_141]
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286) ~[?:1.8.0_141]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120) ~[?:1.8.0_141]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72) ~[?:1.8.0_141]
	at java.lang.Class.createAnnotationData(Class.java:3521) ~[?:1.8.0_141]
	at java.lang.Class.annotationData(Class.java:3510) ~[?:1.8.0_141]
	at java.lang.Class.createAnnotationData(Class.java:3526) ~[?:1.8.0_141]
	at java.lang.Class.annotationData(Class.java:3510) ~[?:1.8.0_141]
	at java.lang.Class.getAnnotation(Class.java:3415) ~[?:1.8.0_141]
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258) ~[?:1.8.0_141]
	at java.lang.Class.isAnnotationPresent(Class.java:3425) ~[?:1.8.0_141]
	at org.jboss.resteasy.plugins.spring.SpringBeanProcessor.processBean(SpringBeanProcessor.java:294) ~[resteasy-spring-3.1.4.Final.jar:3.1.4.Final]
	at org.jboss.resteasy.plugins.spring.SpringBeanProcessor.postProcessBeanFactory(SpringBeanProcessor.java:271) ~[resteasy-spring-3.1.4.Final.jar:3.1.4.Final]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:179) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:693) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]

**Comment by fabiocarvalho777** [comment]
Hi,

Spring Boot 2.0 is not supported yet. Also, we have been collaborating with RESTEasy team and this starter, which was originally developed by PayPal, has been adopted by RESTEasy team itself. The code has been moved to their Git org already, but their first released has not been announced yet. Probably that very first release will support Spring Boot 2.

After that happens, I will freeze development in this Git repo, so that the start can evolve only in the RESTEasy org.

I recommend you watch https://github.com/resteasy/resteasy-spring-boot.

Regards,
Fabio Carvalho.

**Comment by jens-meiss** [comment]
Hi,

i thought it would be a good idea to create a similar ticket and subscribe to it in

* https://github.com/resteasy/resteasy-spring-boot

to get some status updates, since the development here seem stopped as you said, but the "Issues" tab is not visible yet (at least for none project members).

Do you have any news about a roadmap for the first release of resteasy/resteasy-spring-boot?

We would like to use spring-boot 2.0 for all of our new microservice but can't until the resteasy-spring-boot-starter supports it ...

**Comment by fabiocarvalho777** [comment]
Hello Jens,

You made some good points.
I will let @asoldano answer it. He is the person responsible for RESTEasy repo for this starter.

Thanks.

**Comment by jens-meiss** [comment]
thx!

for anyone else who lands here, until the RestEasy support is available for Spring-Boot 2.0 maybe the 
starter-jersey is an alternative for you ...

<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-jersey</artifactId>
</dependency>

**Comment by asoldano** [comment]
@fabiocarvalho777 @jens-meiss I'm thinking about an initial release from https://github.com/resteasy/resteasy-spring-boot with pretty much what we currently have on master there (basically, beside the refactoring related to the sources' move, I've made the project compile with JDK9 and JDK10).
Spring Boot 2 support would come later.
As for the issue tab not being visible, that's on purpose. The idea is to use RESTEasy jira, https://issues.jboss.org/projects/RESTEASY : there's a component named "Spring / Spring Boot" there and a release named "spring-boot-starter-1.0.0.Beta1". Btw, the jira for Spring Boot 2 integration is https://issues.jboss.org/browse/RESTEASY-1852 .
This said, hopefully, we'll be blogging /announcing on this move soon (maybe next week).

**Comment by jens-meiss** [comment]
@asoldano thx for the info, i created a feature request ticket in your jira

* https://issues.jboss.org/browse/RESTEASY-1867
